In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [3]:
from google.colab import files
uploaded = files.upload()

Saving melb_data.csv to melb_data.csv

In [4]:
DATA_PATH ="melb_data.csv"

df = pd.read_csv(DATA_PATH)
print("Shape:",df.shape)
df.head()

Shape: (13580, 21)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [8]:
#Target
y =df['Price']

#Feature
x = df.drop(columns=['Price'])
x.head(2)

,Suburb,Address,Rooms,Type,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0

In [ ]:
X.drop(columns = ['Lattitude', 'Longtitude'], axis = 1, inplace = True)

In [21]:
x.drop(columns = ['SellerG'], axis = 1, inplace = True)

In [22]:
print(x.columns)

Index(['Suburb', 'Rooms', 'Type', 'Method', 'Date', 'Distance', 'Postcode',
       'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'YearBuilt',
       'CouncilArea', 'Regionname'],
      dtype='object')

In [15]:
x.columns

Index(['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Date', 'Distance',
       'Postcode', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea',
       'YearBuilt', 'CouncilArea', 'Regionname'],
      dtype='object')

In [ ]:
#FeatureEngineering
x['Date']=pd.to_datetime(x['Date'],errors='coerce',dayfirst= True)
x['Year']=x['Date'].dt.year
x['Month']=x['Date'].dt.month
x['Day']=x['Date'].dt.day

x.drop(columns = ['Date'], axis = 1, inplace = True)

In [28]:
x.head(3)

,Suburb,Rooms,Type,Method,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Regionname,Month,Day,Year
0,Abbotsford,2,h,S,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra,Northern Metropolitan,12,3,2016
1,Abbotsford,2,h,S,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra,Northern Metropolitan,2,4,2016
2,Abbotsford,3,h,SP,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra,Northern Metropolitan,3,4,2017

In [29]:
num_x = x.select_dtypes(include="number")
cat_x = x.select_dtypes(exclude="number")

In [34]:
# preprocessing

num_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaling", StandardScaler())
])

cat_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", num_transformer, num_x),
        ("cat", cat_transformer, cat_x)
    ],
    remainder="drop"
)

preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaling',
                                                  StandardScaler())]),
                                        Rooms  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  \
0          2       2.5    3067.0       2.0       1.0  1.0     202.0
1          2       2.5    3067.0       2.0       1.0  0.0     156.0
2          3       2.5    3067.0       3.0       2.0  0.0     134.0
3          3       2.5    3067.0       3.0       2.0  1.0      94.0
4          4       2.5    3067.0       3.0       1.0  2.0     120.0
...      ...       ...       ...       ...       ...  ...       ...
13575      4      16.7    3150.0       4.0       2.0...
2         Abbotsford    h     SP       Yarra       Northern Metropolitan
3         Abbotsford    h     PI       Yarra       Northern Metropolitan
4         Abbotsford    h     VB       Yarra       Northern Metropolitan
...              ...  ...    ...         ...                         ...
13575  Wheelers Hill    h      S         NaN  South-Eastern Metropolitan
13576   Williamstown    h     SP         NaN        Western Metropolitan
13577   Williamstown    h      S         NaN        Western Metropolitan
13578   Williamstown    h     PI         NaN        Western Metropolitan
13579     Yarraville    h     SP         NaN        Western Metropolitan

[13580 rows x 5 columns])])

In [35]:
cat_x.head(5)

       Suburb Type Method CouncilArea             Regionname
0  Abbotsford    h      S       Yarra  Northern Metropolitan
1  Abbotsford    h      S       Yarra  Northern Metropolitan
2  Abbotsford    h     SP       Yarra  Northern Metropolitan
3  Abbotsford    h     PI       Yarra  Northern Metropolitan
4  Abbotsford    h     VB       Yarra  Northern Metropolitan

In [37]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15)

In [39]:
x_test.shape

(2037, 17)

In [41]:
model =LinearRegression()
final_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", model)
])
final_pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                         Rooms  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  \
0          2       2.5    3067.0       2.0       1.0  1.0     202.0
1          2       2.5    3067.0       2.0       1.0  0.0     156.0
2          3       2.5    3067.0       3.0       2.0  0.0     134.0
3          3       2.5    3067.0       3.0       2.0  1.0      94.0
4          4       2.5    3067.0       3.0       1.0  2.0     120.0
...      ...       ...       ...       .....
3         Abbotsford    h     PI       Yarra       Northern Metropolitan
4         Abbotsford    h     VB       Yarra       Northern Metropolitan
...              ...  ...    ...         ...                         ...
13575  Wheelers Hill    h      S         NaN  South-Eastern Metropolitan
13576   Williamstown    h     SP         NaN        Western Metropolitan
13577   Williamstown    h      S         NaN        Western Metropolitan
13578   Williamstown    h     PI         NaN        Western Metropolitan
13579     Yarraville    h     SP         NaN        Western Metropolitan

[13580 rows x 5 columns])])),
                ('model', LinearRegression())])

In [43]:
num_x = x_train.select_dtypes(include=['int64', 'float64']).columns
cat_x = x_train.select_dtypes(include=['object']).columns

In [44]:
print(type(num_x))
print(type(cat_x))

<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.base.Index'>